defaults:
  - medium
  - _self_

meta_world: true

im_w: 84
im_h: 84

task_name: button-press-topdown-v2
exp_group: button_press_topdown_84

cmc_file: cmc_exp_local/${exp_group}/1/snapshot.pt
video_dir: videos/${exp_group}/exp

enc_batch_size: 16
episode_len: 50

context_changer:
  _target_: context_changers.NullContextChanger

