defaults:
  - medium
  - _self_

meta_world: true

im_w: 224
im_h: 224
to_lab: 224

task_name: button-press-v2
exp_group: button_press_224

max_num_encoder_videos: 1500

expert_file: exp_local/${task_name}/1/snapshot.pt
cmc_file: cmc_exp_local/${exp_group}/1/snapshot.pt
video_dir: videos/${exp_group}/exp

enc_batch_size: 16
episode_len: 50

context_changer:
  _target_: context_changers.NullContextChanger

