defaults:
  - medium
  - _self_

meta_world: true

task_name: button-press-topdown-v2
exp_group: button_press_topdown

expert_file: exp_local/${task_name}/1/snapshot.pt
cmc_file: cmc_exp_local/${exp_group}/1/snapshot.pt
video_dir: videos/${exp_group}/exp

enc_batch_size: 16
episode_len: 60

context_changer:
  _target_: context_changers.NullContextChanger

