defaults:
  - medium
  - _self_

task_name: finger_turn_easy
exp_group: finger_turn_easy

cmc_file: cmc_exp_local/${exp_group}/1/snapshot.pt
video_dir: videos/${exp_group}/exp

enc_batch_size: 16
episode_len: 60

context_changer:
  _target_: context_changers.NullContextChanger
