defaults:
  - medium
  - _self_

task_name: finger_turn_easy
exp_group: finger_turn_easy_84

expert_file: exp_local/${task_name}/1/snapshot.pt
cmc_file: cmc_exp_local/${exp_group}/1/snapshot.pt
video_dir: videos/${exp_group}/exp

enc_batch_size: 16
episode_len: 50
im_w: 84
im_h: 84

context_changer:
  _target_: context_changers.NullContextChanger
