exp_group: button_press_224

train_video_dir: videos/${exp_group}/train
valid_video_dir: videos/${exp_group}/valid
train_cams: [0]

im_w: 224
im_h: 224

episode_len: 50
batch_size: 16
num_epochs: 8001

cmc_model:
  _target_: cmc_model.CMCEfficientNetB0224
  lr: 1e-4
  hidden_dim: 128
  rho: 1